version: "3.9"
services:
  ecom-micro:
    build: .
    ports:
      - "3000:6553"
    volumes:
      - /Users/rajatkotian/Documents/my_porfolio_projects/ecommerce-microservices:/app
  redis:
    image: "redis"
    ports:
      - "6309:6379"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
networks:
  node-network:
    driver: bridge